---
- name: "System | Update pacman | {{ ansible_distribution }}"
  community.general.pacman:
    update_cache: true
    upgrade: true
    state: latest
  become: true

- name: "System | Install | {{ ansible_distribution }}"
  community.general.pacman:
    name:
      - jq
    state: present
  become: true
