---
- name: "System | Update APT Repos and Upgrade APT Packages | {{ ansible_distribution }}"
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
    autoremove: true
    autoclean: true
  become: true

- name: "System | Install | {{ ansible_distribution }}"
  ansible.builtin.apt:
    name:
      - jq
    state: present
  become: true
